[server]
headless = false
port = 8501

[logger]
level = "error"

[client]
showErrorDetails = false

[runner]
fastReruns = true
magicEnabled = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
